version: '3'

services:
  digdag-a:
    build: ./digdag-server
    ports:
      - 6543:6543
    container_name: digdag-a
  digdag-b:
    build: ./digdag-server
    ports:
      - 6544:6543
    container_name: digdag-b
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: rootpass
