version: '3'

services:
  digdag-a:
    build: ./digdag-server
    ports:
      - 65432:65432
    container_name: digdag-a
  # digdag-b:
  #   build: ./digdag-server
  #   ports:
  #     - 65431:65432
  #   container_name: digdag-b
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: digdag
    command: postgres -c 'max_connections=1024'
    container_name: digdag-db
